import std::
    future -> all_for_one
    env ->
        args
        pwd
    fs ->
        read_file
        path::join

func main() -> Future[Void]
    let files = args
        .split(" ")
        .map(func file
            join(pwd(), file)
                .read_file()
        )
        .all_for_one()
        .use

    for result in files
        match result
            Okay: file
                print(file.content)
            Error: reason
                print("An error occurred: ${reason}")
                return
